### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by hnakamur** [hitoshin/shuca#3]
Could you add the LICENSE file?

These pages may be helpful for choosing a license:
"Choosing an OSS license doesn’t need to be scary - ChooseALicense.com"
http://choosealicense.com/
"Githubによる、オープンソースライセンスの選び方 | オープンソース・ライセンスの談話室"
http://www.catch.jp/oss-license/2013/09/10/github/

**Comment by hitoshin** [comment]
Hi, I am sorry for this very late reply. I have set Apache License 2.0 on this software.

**Comment by hnakamur** [comment]
Thanks!
